services:
  caddy:
    image: caddy:2.11@sha256:2acb10cebb92eea91a40b76691aff73adde9151416facbeab630bbc66d0969ab
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:3000:3000
      - 127.0.0.1:3001:3001
      - 127.0.0.1:3002:3002
      - 127.0.0.1:3003:3004
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - caddy
    environment:
      - FQDN=$FQDN
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY

  litellm:
    image: ghcr.io/berriai/litellm:v1.83.3-stable@sha256:1bc003a50e5c9177909975e1523cf780a5f385c76216e26e96c50fb02611209f
    restart: unless-stopped
    volumes:
      - ./litellm_config.yaml:/app/litellm_config.yaml
      - $GOOGLE_CREDENTIAL_PATH:/app/google_credentials.json
    networks:
      - caddy
      - database
      - ollama
    command: ["--config", "/app/litellm_config.yaml", "--port", "4000", "--num_workers", "4"]
    environment:
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
      - GOOGLE_VERTEX_LOCATION=$GOOGLE_VERTEX_LOCATION
      - GOOGLE_VERTEX_PROJECT=$GOOGLE_VERTEX_PROJECT
      - GROQ_API_KEY=$GROQ_API_KEY
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - POSTGRES_DB_URL=postgresql://$DATABASE_USER:$DATABASE_PASS@$DATABASE_HOST:5432/$DATABASE_NAME
      - LITELLM_MASTER_KEY=$LITELLM_MASTER_KEY
      - UI_PASSWORD=$LITELLM_UI_PASSWORD
      - UI_USERNAME=$LITELLM_UI_USERNAME

  database:
    image: postgres:18.3@sha256:52e6ffd11fddd081ae63880b635b2a61c14008c17fc98cdc7ce5472265516dd0
    restart: unless-stopped
    shm_size: 128mb
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - database
    environment:
      - POSTGRES_USER=$DATABASE_USER
      - POSTGRES_PASSWORD=$DATABASE_PASS

  ollama:
    image: ollama/ollama:0.20.7@sha256:487324a9312240e3e122446f351b1f1e3f68d884ef854c246db2e08792440d94
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - ./models:/models
    ports:
      - 127.0.0.1:11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    networks:
      - ollama
    profiles:
      - gpu
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  anythingllm:
    image: mintplexlabs/anythingllm:1.12.0@sha256:4245dd11e0f94d4ee60e5639984fbce0e90b11b589b572ee8811749a218cd41b
    restart: unless-stopped
    init: true
    volumes:
      - anythingllm:/app/server/storage
      - ./.anythingllm.env:/app/server/.env
    networks:
      - caddy
    environment:
      - DISABLE_TELEMETRY=true
      - DISABLE_VIEW_CHAT_HISTORY=true
      - EMBEDDING_ENGINE=native
      - LITE_LLM_API_KEY=$LITELLM_MASTER_KEY
      - LITE_LLM_BASE_PATH=http://litellm:4000
      - LITE_LLM_MODEL_PREF=openai-gpt-5-4
      - LITE_LLM_MODEL_TOKEN_LIMIT=16384
      - LLM_PROVIDER=litellm
      - SIMPLE_SSO_ENABLED=true
      - SIMPLE_SSO_NO_LOGIN=true
      - SIMPLE_SSO_NO_LOGIN_REDIRECT=https://anything.$FQDN/auth
      - STORAGE_DIR=/app/server/storage
      - VECTOR_DB=lancedb

  anythingllm-auth:
    build: anythingllm-auth
    restart: unless-stopped
    init: true
    networks:
      - caddy
    environment:
      - ANYTHINGLLM_API_TOKEN=$ANYTHINGLLM_API_TOKEN

  open-webui:
    image: ghcr.io/open-webui/open-webui:v0.8.12@sha256:8113fa5510020ef05a44afc0c42d33eabeeb2524a996e3e3fb8c437c00f0d792
    restart: unless-stopped
    init: true
    volumes:
      - ollama-webui:/app/backend/data
    networks:
      - caddy
      - ollama
    environment:
      - DEFAULT_USER_ROLE=user
      - ENABLE_ADMIN_CHAT_ACCESS=false
      - ENABLE_ADMIN_EXPORT=false
      - ENABLE_FORWARD_USER_INFO_HEADERS=true
      - OLLAMA_BASE_URL=http://ollama:11434
      - OPENAI_API_BASE_URL=http://litellm:4000
      - OPENAI_API_KEY=$LITELLM_MASTER_KEY
      - WEBUI_AUTH_TRUSTED_EMAIL_HEADER=$WEBUI_AUTH_TRUSTED_EMAIL_HEADER
      - WEBUI_AUTH_TRUSTED_NAME_HEADER=$WEBUI_AUTH_TRUSTED_NAME_HEADER
      #- BYPASS_MODEL_ACCESS_CONTROL=true

  ollama-webui:
    image: ollama-webui:local
    restart: unless-stopped
    init: true
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - OPENAI_API_KEY=$LITELLM_MASTER_KEY
    networks:
      - caddy
      - ollama
    profiles:
      - custom-ui

networks:
  caddy:
  database:
  ollama:
volumes:
  anythingllm:
  caddy_config:
  caddy_data:
  postgres_data:
  ollama-webui:
  ollama:
