version: "3.9"

services:
  caddy:
    image: caddy:2.7
    restart: unless-stopped
    ports:
      - 3000:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ollama
    environment:
      - FQDN=$FQDN
      - OPENAI_API_KEY=$OPENAI_API_KEY

  litellm:
    image: ghcr.io/berriai/litellm:main-latest
    volumes:
      - ./proxy_server_config.yaml:/app/proxy_server_config.yaml
      - ./.google_credentials.json:/app/google_credentials.json
    networks:
      - ollama
    ports:
      - 4000:4000
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/google_credentials.json
      - OPENAI_API_KEY=$OPENAI_API_KEY
      - ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY
      - UI_USERNAME=$UI_USERNAME
      - UI_PASSWORD=$UI_PASSWORD

  ollama:
    image: ollama/ollama
    restart: unless-stopped
    volumes:
      - ollama:/root/.ollama
      - ./models:/models
    ports:
      - 11434:11434
    environment:
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_ORIGINS=*
    networks:
      - ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  ollama-webui-local:
    image: ollama-webui:local
    restart: unless-stopped
    init: true
    ports:
      - 3001:8080
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    networks:
      - ollama

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    restart: unless-stopped
    init: true
    volumes:
      - ollama-webui:/app/backend/data
    ports:
      - 3002:8080
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
      - OPENAI_API_BASE_URL=http://caddy/openai/v1
    networks:
      - ollama

  ollama-webui-lite:
    image: ollama-webui-lite:main
    restart: unless-stopped
    ports:
      - 3003:80
    networks:
      - ollama

  yakgpt:
    image: yakgpt/yakgpt:latest
    restart: unless-stopped
    ports:
      - 3004:3000
    networks:
      - ollama

  nextchat:
    image: nextchat:custom
    restart: unless-stopped
    ports:
      - 3005:3000
    networks:
      - ollama
    environment:
      - OPENAI_API_KEY=any
      - GOOGLE_API_KEY=
      - CODE=
      - BASE_URL=http://caddy/openai
      - OPENAI_ORG_ID=
      - HIDE_USER_API_KEY=1
      - DISABLE_GPT4=
      - ENABLE_BALANCE_QUERY=
      - DISABLE_FAST_LINK=
      - OPENAI_SB=
      - CUSTOM_MODELS=-all,gpt-3.5-turbo,gpt-4-1106-preview=gpt-4-turbo

networks:
  ollama:

volumes:
  ollama:
  ollama-webui:
  caddy_data:
  caddy_config:
