model_list:
  - model_name: openai-gpt-3.5-turbo
    litellm_params:
      # https://platform.openai.com/docs/models/gpt-3-5-turbo
      model: gpt-3.5-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-gpt-4-turbo
    litellm_params:
      # https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4
      model: gpt-4-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-gpt-4-turbo-preview
    litellm_params:
      # https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4
      model: gpt-4-turbo-preview
      api_key: os.environ/OPENAI_API_KEY
  - model_name: google-gemini-1.5-pro
    litellm_params:
      # https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versioning
      model: vertex_ai/gemini-1.5-pro-preview-0409
      vertex_project: os.environ/GOOGLE_VERTEX_PROJECT
      vertex_location: os.environ/GOOGLE_VERTEX_LOCATION
  - model_name: anthropic-claude-3-sonnet
    litellm_params:
      # https://docs.anthropic.com/claude/docs/models-overview
      model: claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic-claude-3-opus
    litellm_params:
      # https://docs.anthropic.com/claude/docs/models-overview
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: local-mistral
    litellm_params:
      model: ollama/mistral:latest
      api_base: http://ollama:11434
  - model_name: local-mixtral-8x7b
    litellm_params:
      model: ollama/mixtral:8x7b
      api_base: http://ollama:11434
  - model_name: local-google-gemma
    litellm_params:
      model: ollama/gemma:latest
      api_base: http://ollama:11434

litellm_settings:
  drop_params: True
  max_budget: 100
  budget_duration: 30d
  num_retries: 5
  request_timeout: 600

general_settings:
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 60
  database_url: os.environ/POSTGRES_DB_URL
