model_list:
  - model_name: openai-gpt-4-turbo
    litellm_params:
      # https://platform.openai.com/docs/models/gpt-4-turbo
      model: gpt-4-turbo
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-gpt-4o
    litellm_params:
      # https://platform.openai.com/docs/models/gpt-4o
      model: gpt-4o
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-o3
    litellm_params:
      # https://platform.openai.com/docs/models/o3
      model: o3
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-o4-mini
    litellm_params:
      # https://platform.openai.com/docs/models/o4-mini
      model: o4-mini
      api_key: os.environ/OPENAI_API_KEY
#  - model_name: google-gemini-2.0-flash
#    litellm_params:
#      # https://cloud.google.com/vertex-ai/generative-ai/docs/learn/model-versioning
#      model: vertex_ai/gemini-2.0-flash-001
#      vertex_project: os.environ/GOOGLE_VERTEX_PROJECT
#      vertex_location: os.environ/GOOGLE_VERTEX_LOCATION
  - model_name: anthropic-claude-3-7-sonnet
    litellm_params:
      # https://docs.anthropic.com/claude/docs/models-overview
      model: claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic-claude-4-0-sonnet
    litellm_params:
      # https://docs.anthropic.com/claude/docs/models-overview
      model: claude-sonnet-4-20250514
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: groq-llama-3.3-70b
    litellm_params:
      # https://console.groq.com/docs/models
      model: groq/llama-3.3-70b-versatile
      api_key: os.environ/GROQ_API_KEY
  - model_name: groq-llama-4-maverick
    litellm_params:
      # https://console.groq.com/docs/models
      model: groq/meta-llama/llama-4-maverick-17b-128e-instruct
      api_key: os.environ/GROQ_API_KEY
  - model_name: local-google-gemma3
    litellm_params:
      model: ollama/gemma3:27b-it-qat
      api_base: http://ollama:11434
  - model_name: local-llama3-1-8b
    litellm_params:
      model: ollama/llama3.1:8b
      api_base: http://ollama:11434
  - model_name: local-qwen3-32b
    litellm_params:
      model: ollama/qwen3:32b
      api_base: http://ollama:11434
  - model_name: local-qwen3-30b-a3b
    litellm_params:
      model: ollama/qwen3:30b-a3b
      api_base: http://ollama:11434

litellm_settings:
  drop_params: True
  max_budget: 100
  budget_duration: 30d
  num_retries: 2
  request_timeout: 600

general_settings:
  proxy_batch_write_at: 60
  database_url: os.environ/POSTGRES_DB_URL
  user_header_name: X-OpenWebUI-User-Email
