model_list:
  - model_name: openai-gpt-3.5-turbo
    litellm_params:
      model: gpt-3.5-turbo
      api_base: https://api.openai.com/v1/
      api_key: os.environ/OPENAI_API_KEY
  - model_name: openai-gpt-4-turbo-preview
    litellm_params:
      model: gpt-4-turbo-preview
      api_base: https://api.openai.com/v1/
      api_key: os.environ/OPENAI_API_KEY
  - model_name: google-gemini-1.0-pro
    litellm_params:
      model: vertex_ai/gemini-1.0-pro
      vertex_project: "vertex-llm-418003"
      vertex_location: "europe-west3"
  - model_name: anthropic-claude-3-opus
    litellm_params:
      model: claude-3-opus-20240229
      api_key: os.environ/ANTHROPIC_API_KEY
  - model_name: anthropic-claude-3-sonnet
    litellm_params:
      model: claude-3-sonnet-20240229
      api_key: os.environ/ANTHROPIC_API_KEY

litellm_settings:
  drop_params: True
  max_budget: 100
  budget_duration: 30d
  num_retries: 5
  request_timeout: 600

general_settings:
  # master_key: sk-1234 # [OPTIONAL] Only use this if you to require all calls to contain this key (Authorization: Bearer sk-1234)
  proxy_budget_rescheduler_min_time: 60
  proxy_budget_rescheduler_max_time: 64
  proxy_batch_write_at: 1
  # database_url: "postgresql://<user>:<password>@<host>:<port>/<dbname>" # [OPTIONAL] use for token-based auth to proxy
